export const PFLessons = {
    "lessons" : [
          { id: '001', title: 'Programming Foundation Intro', videoUrl: 'idq9WNe593o', watched: false },
          { id: '002', title: 'Computer Program', videoUrl: 'bguxdwZyFQw', watched: false },
          { id: '003', title: 'Programming Environment', videoUrl: '6LiFhrFFlp0', watched: false },
          { id: '004', title: 'Wht JavaScript', videoUrl: '_lIavDwxE8Q', watched: false },
          { id: '005', title: 'First Program', videoUrl: 'HQ7a8SAestw', watched: false },
          { id: '006', title: 'Basic Syntax', videoUrl: 'f16JczV6quY', watched: false },
          { id: '007', title: 'Input', videoUrl: '9dAhJC16-R0', watched: false },
          { id: '008', title: 'Variable', videoUrl: 'OLzKbIV4Afg', watched: false },
          { id: '009', title: 'Data Type', videoUrl: 'c9BnzSb-UCU', watched: false },
          { id: '010', title: 'Keywords', videoUrl: 'vGh9d-DLLSI', watched: false },
          { id: '011', title: 'Number', videoUrl: '-qUs94PfLsM', watched: false },
          { id: '012', title: 'String', videoUrl: 'ab1MtBojJ2E', watched: false },
          { id: '013', title: 'Arithmetic Opeartors', videoUrl: 'HCmRaEFM2-E', watched: false },
          { id: '014', title: 'Assigment Operators', videoUrl: 'tScs4mqwg00', watched: false },
          { id: '015', title: 'White Space', videoUrl: 'JcLoXF6HzO0', watched: false },
          { id: '016', title: 'Comment', videoUrl: 'E8WZyEqC3nw', watched: false },
          { id: '017', title: 'Conditional Code', videoUrl: 'ip48JOe4H88', watched: false },
          { id: '018', title: 'If else, if esle if else', videoUrl: 'fuoRKCdOpcU', watched: false },
          { id: '019', title: 'Comparison and Logical Operators', videoUrl: 'YKaXmuJUrOQ', watched: false },
          { id: '020', title: 'Switch', videoUrl: 'QX983_mAWSw', watched: false },
          { id: '021', title: 'Function', videoUrl: 'GBaYpHxkUyY', watched: false },
          { id: '022', title: 'Creatin and Calling Function', videoUrl: 'Ozr0nSVaV9I', watched: false },
          { id: '023', title: 'Parameters,arguments,return', videoUrl: 'Y9YWQAGN3IM', watched: false },
          { id: '024', title: 'Variable Scope', videoUrl: 'RnonQ7pUvVQ', watched: false },
          { id: '025', title: 'Split File', videoUrl: 'd216NqAL2SQ', watched: false },
          { id: '026', title: 'Introduction to iteration', videoUrl: 'X0vgaKfWSsA', watched: false },
          { id: '027', title: 'While Statement', videoUrl: 'lpMJVIR6zAc', watched: false },
          { id: '028', title: 'For,Do While Statement', videoUrl: 'Z1cV6yyGfN4', watched: false },
          { id: '029', title: 'Concatantion', videoUrl: 'aVvCKM1qB-g', watched: false },
          { id: '030', title: 'String Function', videoUrl: 'bIZjO_zvvLQ', watched: false },
          { id: '031', title: 'Introduction to regular expression', videoUrl: 'ZWHxUrdNM3U', watched: false },
          { id: '032', title: 'Working With Array', videoUrl: '862uLK-16rk', watched: false },
          { id: '033', title: 'Array Behavior', videoUrl: '2XSnK6uqGmc', watched: false },
          { id: '034', title: 'Iterating Through Collection', videoUrl: 'rLiS6gH4XVc', watched: false },
          { id: '035', title: 'Arrays in other language', videoUrl: 'gv4CHVTHi68', watched: false },
          { id: '036', title: 'Programming Style Guideling', videoUrl: 'pAT0I7-PKZM', watched: false },
          { id: '037', title: 'Pseudocode', videoUrl: '4GNktjx7hpg', watched: false },
          { id: '038', title: 'Input output and persistence', videoUrl: 'ntJLdDJV35Y', watched: false },
          { id: '039', title: 'Reading and Writing from DOM', videoUrl: 'ECFyUBnSAEw', watched: false },
          { id: '040', title: 'Event driven programming', videoUrl: 'R6kcMF5_Zis', watched: false },
          { id: '041', title: 'File Input Output', videoUrl: 'lOx3g1gxi70', watched: false },
          { id: '042', title: 'Introduction to debugging', videoUrl: 'PPidtcLwVMg', watched: false },
          { id: '043', title: 'Tracing through a section of code', videoUrl: 'i5OPHRm2npw', watched: false },
          { id: '044', title: 'Understanding error message', videoUrl: 'e1OGkG8HTyU', watched: false },
          { id: '045', title: 'Using Debugger', videoUrl: '75YZclwqzKw', watched: false },
          { id: '046', title: 'Introduction to object oriented languages', videoUrl: 'zKY4r5Pz1_E', watched: false },
          { id: '047', title: 'Using class and objects', videoUrl: 'WhuRtb5KquE', watched: false },
          { id: '048', title: 'Review OOP', videoUrl: 'E3_O3KS5eVU' , watched:false},
          { id:'049' ,title:'Memory management in across languages' ,videoUrl:'KbvgCPG2L4Q' ,watched:false},
          { id:'050' ,title:'Introduction to algorithms' ,videoUrl:'hdN6CZ_5uWI' ,watched:false},
          { id:'051' ,title:'Multithreading' ,videoUrl:'GZVKD5ZhrQE' ,watched:false},
          { id:'052' ,title:'Introduction to Programming Lenguage' ,videoUrl:'Od-pCNZsfHY' ,watched:false},
          { id:'053' ,title:'C based languages' ,videoUrl:'NVDZKeY3HyM' ,watched:false},
          { id:'054' ,title:'Java' ,videoUrl:'yU26VOW3m_M'  ,watched:false},
          { id:'055' ,title:'NET languages CSh VB NET' 	,videoUrl :'9ZHswrCi2AE',
            watched:false},
            {id :'056',
            title :'Ruby',
            videoUrl :'fU9YRlmMp_0',
            watched :false
            },
            {
              id :'057',
              title :'Python',
              videoUrl :'uZs-xpCvKjQ',
              watched :false
            },
            {
              id :'058',
              title :'Objective C',
              videoUrl :'UespfMh_4o0',
              watched :false
            },
            {
              id :'059',
              title :'Libararies and frameworks',
              videoUrl :'myZv_KrxJmc',
              watched :false
            }
        ],
}