export const ScratchLessons = {
    "lessons" : [
          {id: '001', title: 'scratch programming Intro', videoUrl: 'x1GozpBUBa4', watched: false},
          {id: '002', title: 'scratch programming Getting Start', videoUrl: 'Db6I3zKDTlg', watched: false},
          {id: '003', title: 'scratch programming Using Green Flag', videoUrl: 'uxXmbOf-EHs', watched: false},
          {id: '004', title: 'scratch programming Change Background and Add Character', videoUrl: 'gZGkOPANTe4', watched: false},
          {id: '005', title: 'scratch programming Say Something', videoUrl: 'd9T9ZsY7_Ro', watched: false},
          {id: '006', title: 'scratch programming Title Project Name Save Project', videoUrl: 'gNwuivZcSp4', watched: false},
          {id: '007', title: 'scratch programming Key points', videoUrl: 'BiPJsTeNS4M', watched: false},
          {id: '008', title: 'scratch programming User Interface', videoUrl: '1ygOg-MubiQ', watched: false},
          {id: '009', title: 'scratch programming Move Cat', videoUrl: '0Qq9Hw18gx4', watched: false},
          {id: '010', title: 'scratch programming Hop Block', videoUrl: '5pY1Q3n60iQ', watched: false},
          {id: '011', title: 'scratch programming Trun Cat', videoUrl: 'vgJ9l_EPp9g', watched: false},
          {id: '012', title: 'scratch programming Hide and Seek', videoUrl: 'BN5iJVRCaw8', watched: false},
          {id: '013', title: 'scratch programming Repeat and Repeat Forever', videoUrl: 'cl2Dg1AJGD4', watched: false},
          {id: '014', title: 'scratch programming Old MacDonald Farm', videoUrl: 'syazPJK9Mro', watched: false},
          {id: '015', title: 'scratch programming Scratchjr in yourself', videoUrl: '7ifEH86UL3E', watched: false},
          {id: '016', title: 'scratch programming Find Your Voice', videoUrl: 'e9BjnPWZXKk', watched: false},
          {id: '017', title: 'scratch programming Turn The Page', videoUrl: 'O1-0aB0aZBI', watched: false},
          {id: '018', title: 'scratch programming Set Speed Block', videoUrl: 'gaoh1OlXQnU', watched: false},
          {id: '019', title: 'scratch programming Wait', videoUrl: 'lG0I50tBWlY', watched: false},
          {id: '020', title: 'scratch programming Wait Your Turn', videoUrl: 'dHQlYbDVZ2U', watched: false},
          {id: '021', title: 'scratch programming Paint', videoUrl: 'iBQ1tIxguH4', watched: false},
          {id: '022', title: 'scratch programming The Tortoise and The Hear', videoUrl: 'BM6XS9JRUdg', watched: false},
          {id: '023', title: 'scratch programming The Tortoise and the hera', videoUrl: 'exHeyf4sQ18', watched: false},
          {id: '024', title: 'scratch programming Spelling', videoUrl: 'UGA5ah7AVXo', watched: false},
          {id: '025', title: 'scratch programming Pick a Peach', videoUrl: 'k2vPCl99-CE', watched: false},
          {id: '026', title: 'scratch programming Blast OFF!', videoUrl: 'lQxlGzvKtGY', watched: false},
          {id: '027', title: 'scratch programming Play Tag!', videoUrl: 'kui527SM5Ck', watched: false},
          {id: '028', title: 'scratch programming Guess Game', videoUrl: 'xJd6kyXgVHw', watched: false},
          {id: '029', title: 'scratch programming Cat Vs Bird', videoUrl: 'pYO23D8ND7M', watched: false},
          {id: '030', title: 'scratch programming Study other projects', videoUrl: 'R14Hb4z_YoQ', watched: false},
          {id: '031', title:'scratch programming What is Next' ,videoUrl:'ylJAmxfcRW0' ,watched:false },
          {id:'032' ,title:'Move to Sctrach Programming' ,videoUrl:'r1xPv8O-cJQ' ,watched:false },
        ]
}